### ISSUE TITLE
changes in script for install verneMQ in Raspbian Buster

### ISSUE THREAD

**Issue by hamed-ta** [suiluj/pi-adhoc-mqtt-cluster#2]
just change the sctript to this for new version of VerneMQ on Raspbian Buster

```
#!/bin/sh -e
# compiles and installs batman-adv and batctl (version 2018.1)
# create file: 'nano vernemqinstall' and copy this text
# then run: 'sh ./vernemqinstall'
# important not to sudo then vernemq without sudo possible
# reboot after install


sudo apt-get update
sudo apt-get install wget -y
sudo apt-get install libssl-dev -y
sudo apt-get install libssh-dev -y
sudo apt-get install ncurses-dev -y

cd /home/pi
wget http://erlang.org/download/otp_src_21.2.tar.gz

tar -xzvf otp_src_21.2.tar.gz
cd otp_src_21.2/
./configure

make -j 4 

sudo make install
cd /home/pi
rm otp_src_21.2.tar.gz
sudo rm -R otp_src_21.2/

git clone https://github.com/larshesel/vernemq.git
cd vernemq/
make rpi32

exit 0
```

**Comment by suiluj** [comment]
ah so so in the meantime you do not need to use the special branch anymore?

did you also try the batman scripts and did they work for you? or did you only use vernemq?

**Comment by hamed-ta** [comment]
> ah so so in the meantime you do not need to use the special branch anymore?

no, not anymore.

> did you also try the batman scripts and did they work for you? or did you only use vernemq?

I haven't tested it, I just needed to compile and install verneMQ.

**Comment by suiluj** [comment]
okay thanks for your info i will update the vernemq script.
